language: r
dist: trusty
sudo: required
cache: packages

apt_packages:
- libudunits2-dev

r_packages:
   - dplyr
   - Rcpp
   - rgdal
   - rgeos
   - raster

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev netcdf-bin

## Set up the matrix of different runs
env:
  matrix:
  - r: release
    not_cran: true
    r_check_args: "--no-manual"
  - r: release
    not_cran: false
    r_check_args: "--no-manual --as--cran"

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
    - devtools

r_github_packages:
    - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
